name: Build Release

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Windows
            os: windows-latest
          - platform: macOS
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
    # -------------------------
      # Windows
      # -------------------------

      - name: Build Windows
        if: runner.os == 'Windows'
        run: flutter build windows --release

      - name: Upload Windows build
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-${{ github.ref_name }}
          path: build/windows/x64/runner/Release/

      # -------------------------
      # macOS
      # -------------------------

      - name: Build macOS
        if: runner.os == 'macOS'
        run: flutter build macos --release

      - name: Upload macOS build
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: macos-release-${{ github.ref_name }}
          path: build/macos/Build/Products/Release/
